### ISSUE TITLE
installation error - missing hook method onOutputPageBodyAttributes()

### ISSUE THREAD

**Issue by m3w88** [AmazingWikis/UserBoard#11]
MediaWiki internal error.

Original exception: [7e37580a5e8edabdd98db1ef] /wiki/MediaWiki:Common.js Error: Call to undefined method UserBoardHooks::onOutputPageBodyAttributes()
Backtrace:
from /var/www/html/w/includes/HookContainer/HookContainer.php(338)
#0 /var/www/html/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#1 /var/www/html/w/includes/HookContainer/HookRunner.php(2694): MediaWiki\HookContainer\HookContainer->run()
#2 /var/www/html/w/includes/OutputPage.php(3420): MediaWiki\HookContainer\HookRunner->onOutputPageBodyAttributes()
#3 /var/www/html/w/includes/skins/SkinMustache.php(63): OutputPage->headElement()
#4 /var/www/html/w/includes/skins/SkinTemplate.php(177): SkinMustache->generateHTML()
#5 /var/www/html/w/includes/OutputPage.php(2876): SkinTemplate->outputPage()
#6 /var/www/html/w/includes/MediaWiki.php(922): OutputPage->output()
#7 /var/www/html/w/includes/MediaWiki.php(562): MediaWiki->main()
#8 /var/www/html/w/index.php(50): MediaWiki->run()
#9 /var/www/html/w/index.php(46): wfIndexMain()
#10 {main}

Exception caught inside exception handler: [7e37580a5e8edabdd98db1ef] /wiki/MediaWiki:Common.js Error: Call to undefined method UserBoardHooks::onOutputPageBodyAttributes()
Backtrace:
from /var/www/html/w/includes/HookContainer/HookContainer.php(338)
#0 /var/www/html/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#1 /var/www/html/w/includes/HookContainer/HookRunner.php(2694): MediaWiki\HookContainer\HookContainer->run()
#2 /var/www/html/w/includes/OutputPage.php(3420): MediaWiki\HookContainer\HookRunner->onOutputPageBodyAttributes()
#3 /var/www/html/w/includes/skins/SkinMustache.php(63): OutputPage->headElement()
#4 /var/www/html/w/includes/skins/SkinTemplate.php(177): SkinMustache->generateHTML()
#5 /var/www/html/w/includes/OutputPage.php(2876): SkinTemplate->outputPage()
#6 /var/www/html/w/includes/exception/MWExceptionRenderer.php(183): OutputPage->output()
#7 /var/www/html/w/includes/exception/MWExceptionRenderer.php(102): MWExceptionRenderer::reportHTML()
#8 /var/www/html/w/includes/exception/MWExceptionHandler.php(131): MWExceptionRenderer::output()
#9 /var/www/html/w/includes/exception/MWExceptionHandler.php(248): MWExceptionHandler::report()
#10 /var/www/html/w/includes/MediaWiki.php(584): MWExceptionHandler::handleException()
#11 /var/www/html/w/index.php(50): MediaWiki->run()
#12 /var/www/html/w/index.php(46): wfIndexMain()
#13 {main}

**Comment by m3w88** [comment]
OS: Ubuntu 22.04
PHP 8.1.2
MediaWiki 1.39.8

userboard.sql was run by update.php, there is undefined method referenced from socialprofile

This is for a wikifarm set up using $wgLocalDatabases, $wgSharedDB, $wgSharedTables in the following configuration:
$wgLocalDatabases = array(
);
 
$wikis = [
	"domain" => "database_name",
];


if (defined('MW_DB')) {
	// Automatically set from --wiki option to maintenance scripts.
	$wiki_ID = MW_DB;
}
else {
	// Use MW_DB environment variable or map the domain name
	/$wikiID = $_SERVER['MW_DB'] ?? $wikis[ $_SERVER['SERVER_NAME'] ?? '' ] ?? null;
}

switch ($wiki_ID) {
	case 'database_name':
		require_once 'LocalSettings_wikiname.php';
		break;
}

**Comment by m3w88** [comment]
userboards was originally a module displayed on socialprofile's userprofilepage, the undefined method is suspected to be a reference to this.
